"""quizcards sm-2 update

Revision ID: 5b45cf782024
Revises: 0efeff63eab1
Create Date: 2026-04-15 14:47:16.013819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b45cf782024'
down_revision: Union[str, Sequence[str], None] = '0efeff63eab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('repetition_count', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('ease_factor', sa.Float(), nullable=True))
    op.add_column('card', sa.Column('day_interval', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('next_review', sa.DateTime(), nullable=True))
    op.add_column('quizcard', sa.Column('repetition_count', sa.Integer(), nullable=True))
    op.add_column('quizcard', sa.Column('ease_factor', sa.Float(), nullable=True))
    op.add_column('quizcard', sa.Column('day_interval', sa.Integer(), nullable=True))
    op.add_column('quizcard', sa.Column('next_review', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizcard', 'next_review')
    op.drop_column('quizcard', 'day_interval')
    op.drop_column('quizcard', 'ease_factor')
    op.drop_column('quizcard', 'repetition_count')
    op.drop_column('card', 'next_review')
    op.drop_column('card', 'day_interval')
    op.drop_column('card', 'ease_factor')
    op.drop_column('card', 'repetition_count')
    # ### end Alembic commands ###
