"""card explanation type

Revision ID: eaa92c82a509
Revises: e4b96f3700f1
Create Date: 2026-04-23 15:57:35.827109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eaa92c82a509'
down_revision: Union[str, Sequence[str], None] = 'e4b96f3700f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('back', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quizcard', sa.Column('back', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizcard', 'back')
    op.drop_column('card', 'back')
    # ### end Alembic commands ###
